apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-griffin-employee
  name: service-griffin-employee
  namespace: default
spec:
  ports:
  - port: 8900
    protocol: TCP
    targetPort: 8080
  selector:
    app: griffin-employee-pod
  sessionAffinity: None
  type: LoadBalancer